import {
  User,
  IdCard,
  Phone,
  Mail,
  Baby,
  Calendar,
  School,
  AlertTriangle,
  HeartPulse,
  MessageSquare,
} from "lucide-react";

import type { Step } from "@/types/form";

export const steps: Step[] = [
  {
    id: "guardianName",
    title: "Qual é o seu nome completo?",
    description: "Quero te conhecer melhor 😊",
    placeholder: "Digite seu nome completo",
    type: "text",
    icon: User,
    required: true,
  },
  {
    id: "guardianCpf",
    title: "Agora me informe seu CPF",
    description: "Pode digitar só os números",
    placeholder: "000.000.000-00",
    type: "cpf",
    icon: IdCard,
    required: true,
  },
  {
    id: "guardianPhone",
    title: "Qual é o seu telefone?",
    description: "Com DDD, por favor",
    placeholder: "(21) 99999-9999",
    type: "phone",
    icon: Phone,
    required: true,
  },
  {
    id: "guardianEmail",
    title: "Quer deixar um e-mail também?",
    description: "Esse campo é opcional",
    placeholder: "nome@email.com",
    type: "email",
    icon: Mail,
    required: false,
  },
  {
    id: "studentName",
    title: "Qual é o nome do aluno?",
    description: "Nome completo, por favor",
    placeholder: "Nome do aluno",
    type: "text",
    icon: Baby,
    required: true,
  },
  {
    id: "studentBirthdate",
    title: "Qual é a data de nascimento?",
    description: "Exemplo: 19/04/2020",
    placeholder: "DD/MM/AAAA",
    type: "date",
    icon: Calendar,
    required: true,
  },
  {
    id: "studentGrade",
    title: "Qual série ele(a) vai cursar?",
    description: "Se não souber, pode dizer: Não sei ainda",
    placeholder: "Ex: 7º ano",
    type: "text",
    icon: School,
    required: true,
  },
  {
    id: "studentAllergies",
    title: "O aluno tem alguma alergia?",
    description: "Se não tiver, escreva: Nenhuma",
    placeholder: "Ex: Derivados do leite",
    type: "text",
    icon: AlertTriangle,
    required: true,
  },
  {
    id: "studentSpecialNeeds",
    title: "Existe alguma necessidade especial?",
    description: "Pode responder: Sim ou Não",
    placeholder: "Sim ou Não",
    type: "text",
    icon: HeartPulse,
    required: true,
  },
  {
    id: "studentNotes",
    title: "Quer adicionar alguma observação?",
    description: "Esse campo é opcional",
    placeholder: "Digite aqui...",
    type: "textarea",
    icon: MessageSquare,
    required: false,
  },
];